
export const dieBlueprints = [
  {
    id: 'die.patches.utility',
    heroId: 'patches',
    name: 'Utility Die',
    shortName: 'UTL',
    code: 'UTL',
    accent: '#7ed3ff',
    visualAssetId: 'die.patches.utility',
    faces: [
      {
        id: 'dieFace.patches.utility.wrench',
        name: 'Wrench',
        shortName: 'Wrench',
        shortLabel: 'WR',
        visualAssetId: 'dieFace.patches.utility.wrench',
        meaning: 'repair support',
      },
      {
        id: 'dieFace.patches.utility.medkit',
        name: 'Medkit',
        shortName: 'Medkit',
        shortLabel: 'MD',
        visualAssetId: 'dieFace.patches.utility.medkit',
        meaning: 'heal support',
      },
      {
        id: 'dieFace.patches.utility.spark',
        name: 'Spark',
        shortName: 'Spark',
        shortLabel: 'SP',
        visualAssetId: 'dieFace.patches.utility.spark',
        meaning: 'tech trigger',
      },
      {
        id: 'dieFace.patches.utility.drone',
        name: 'Drone',
        shortName: 'Drone',
        shortLabel: 'DR',
        visualAssetId: 'dieFace.patches.utility.drone',
        meaning: 'helper setup',
      },
      {
        id: 'dieFace.patches.utility.patch',
        name: 'Patch',
        shortName: 'Patch',
        shortLabel: 'PT',
        visualAssetId: 'dieFace.patches.utility.patch',
        meaning: 'recovery',
      },
      {
        id: 'dieFace.patches.utility.overclock',
        name: 'Overclock',
        shortName: 'Boost',
        shortLabel: 'OC',
        visualAssetId: 'dieFace.patches.utility.overclock',
        meaning: 'boost utility',
      },
    ],
  },
  {
    id: 'die.picket.guard',
    heroId: 'picket',
    name: 'Guard Die',
    shortName: 'GRD',
    code: 'GRD',
    accent: '#ffb067',
    visualAssetId: 'die.picket.guard',
    faces: [
      {
        id: 'dieFace.picket.guard.shield',
        name: 'Shield',
        shortName: 'Shield',
        shortLabel: 'SH',
        visualAssetId: 'dieFace.picket.guard.shield',
        meaning: 'block hit',
      },
      {
        id: 'dieFace.picket.guard.brace',
        name: 'Brace',
        shortName: 'Brace',
        shortLabel: 'BR',
        visualAssetId: 'dieFace.picket.guard.brace',
        meaning: 'steady defense',
      },
      {
        id: 'dieFace.picket.guard.taunt',
        name: 'Taunt',
        shortName: 'Taunt',
        shortLabel: 'TA',
        visualAssetId: 'dieFace.picket.guard.taunt',
        meaning: 'frontline control',
      },
      {
        id: 'dieFace.picket.guard.spike',
        name: 'Spike',
        shortName: 'Spike',
        shortLabel: 'SK',
        visualAssetId: 'dieFace.picket.guard.spike',
        meaning: 'retaliation',
      },
      {
        id: 'dieFace.picket.guard.hold',
        name: 'Hold',
        shortName: 'Hold',
        shortLabel: 'HD',
        visualAssetId: 'dieFace.picket.guard.hold',
        meaning: 'position hold',
      },
      {
        id: 'dieFace.picket.guard.wall',
        name: 'Wall',
        shortName: 'Wall',
        shortLabel: 'WL',
        visualAssetId: 'dieFace.picket.guard.wall',
        meaning: 'heavy guard',
      },
    ],
  },
  {
    id: 'die.tantrum.fury',
    heroId: 'tantrum',
    name: 'Fury Die',
    shortName: 'FRY',
    code: 'FRY',
    accent: '#ffd166',
    visualAssetId: 'die.tantrum.fury',
    faces: [
      {
        id: 'dieFace.tantrum.fury.rage',
        name: 'Rage',
        shortName: 'Rage',
        shortLabel: 'RG',
        visualAssetId: 'dieFace.tantrum.fury.rage',
        meaning: 'rage build',
      },
      {
        id: 'dieFace.tantrum.fury.smash',
        name: 'Smash',
        shortName: 'Smash',
        shortLabel: 'SM',
        visualAssetId: 'dieFace.tantrum.fury.smash',
        meaning: 'burst hit',
      },
      {
        id: 'dieFace.tantrum.fury.leap',
        name: 'Leap',
        shortName: 'Leap',
        shortLabel: 'LP',
        visualAssetId: 'dieFace.tantrum.fury.leap',
        meaning: 'gap close',
      },
      {
        id: 'dieFace.tantrum.fury.howl',
        name: 'Howl',
        shortName: 'Howl',
        shortLabel: 'HW',
        visualAssetId: 'dieFace.tantrum.fury.howl',
        meaning: 'pressure',
      },
      {
        id: 'dieFace.tantrum.fury.crack',
        name: 'Crack',
        shortName: 'Crack',
        shortLabel: 'CK',
        visualAssetId: 'dieFace.tantrum.fury.crack',
        meaning: 'armor break',
      },
      {
        id: 'dieFace.tantrum.fury.frenzy',
        name: 'Frenzy',
        shortName: 'Frenzy',
        shortLabel: 'FZ',
        visualAssetId: 'dieFace.tantrum.fury.frenzy',
        meaning: 'multi hit',
      },
    ],
  },
  {
    id: 'die.boomer.bomb',
    heroId: 'boomer',
    name: 'Bomb Die',
    shortName: 'BMB',
    code: 'BMB',
    accent: '#ff8a80',
    visualAssetId: 'die.boomer.bomb',
    faces: [
      {
        id: 'dieFace.boomer.bomb.spark',
        name: 'Spark',
        shortName: 'Spark',
        shortLabel: 'SP',
        visualAssetId: 'dieFace.boomer.bomb.spark',
        meaning: 'ignite fuse',
      },
      {
        id: 'dieFace.boomer.bomb.blast',
        name: 'Blast',
        shortName: 'Blast',
        shortLabel: 'BL',
        visualAssetId: 'dieFace.boomer.bomb.blast',
        meaning: 'area burst',
      },
      {
        id: 'dieFace.boomer.bomb.shrapnel',
        name: 'Shrapnel',
        shortName: 'Shard',
        shortLabel: 'SR',
        visualAssetId: 'dieFace.boomer.bomb.shrapnel',
        meaning: 'scatter damage',
      },
      {
        id: 'dieFace.boomer.bomb.fuse',
        name: 'Fuse',
        shortName: 'Fuse',
        shortLabel: 'FU',
        visualAssetId: 'dieFace.boomer.bomb.fuse',
        meaning: 'delay setup',
      },
      {
        id: 'dieFace.boomer.bomb.fire',
        name: 'Fire',
        shortName: 'Fire',
        shortLabel: 'FR',
        visualAssetId: 'dieFace.boomer.bomb.fire',
        meaning: 'burn effect',
      },
      {
        id: 'dieFace.boomer.bomb.kaboom',
        name: 'Kaboom',
        shortName: 'Kaboom',
        shortLabel: 'KB',
        visualAssetId: 'dieFace.boomer.bomb.kaboom',
        meaning: 'big explosion',
      },
    ],
  },
]

export const dieFaceContent = dieBlueprints.flatMap((die) =>
  die.faces.map((face, index) => ({
    id: face.id,
    heroId: die.heroId,
    dieId: die.id,
    name: face.name,
    shortName: face.shortName,
    shortLabel: face.shortLabel,
    meaning: face.meaning,
    sortOrder: index,
    visualAssetId: face.visualAssetId,
  })),
)

export const diceContent = dieBlueprints.map((die) => ({
  id: die.id,
  heroId: die.heroId,
  name: die.name,
  shortName: die.shortName,
  code: die.code,
  accent: die.accent,
  visualAssetId: die.visualAssetId,
  faceIds: die.faces.map((face) => face.id),
}))
